site_name: Coding Muscle with R Geospatial
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.copy
  - toc.integrate
  palette:
  - scheme: default
    primary: indigo
    accent: light-blue
  - scheme: slate
    primary: indigo
    accent: light-blue
nav:
- Home: index.md
- ':material-language-r: R Fundamentals':
  - Basic Data types: 01_Basic_Data_types.md
  - Data Structures: 02_Data_Structures_in_R.md
- ':material-chart-bar: Spatial Data Science':
  - Tidyverse for Spatial: Tidyverse_Spatial.md
  - Vector Analysis (sf): Vector_Analysis_sf.md
  - Raster Processing (terra): Raster_Processing_terra.md
plugins:
- search
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.emoji
